/**
 * Default data for seeding database
 * This data is migrated from frontend hardcoded arrays
 */

const defaultProjects = [
  {
    projectName: 'Surat Textile Hub Phase II',
    location: 'Surat, Gujarat',
    city: 'Surat',
    district: 'Surat',
    category: 'industrial',
    systemSizeKw: 500,
    description: 'Industrial textile hub solar installation',
    caseStudy: '',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCnBtfyqV56kpdIF4RBxj3IqCkN-VSikDVDcNCsMEMfJPMahG7NtiITcQ0pdfWw3jroQiiSeJQxIfHH7VTEtYIFRR33fCKsVdQYMK99p_8LHPD-XrKsh-pEqWcrHmf1EhSyOs3XXBUGTcircoMnZRd_ATDIsWXNSrXswYG8S-GFffIRNrcDT5OcPkVMmrw4TMsIE3M6zS_swAsopUhluhEqXwHhqjWzbX7kymmNBQp3Udw1IgLc84UcUbs0YOnmD06FtNz1D1WuwwwV',
    isMegaProject: false,
    isDefault: true,
  },
  {
    projectName: 'Tech Park Plaza Canopy',
    location: 'Pune, Maharashtra',
    city: 'Pune',
    district: 'Pune',
    category: 'commercial',
    systemSizeKw: 250,
    description: 'Commercial tech park canopy solar system',
    caseStudy: '',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCAtnO2cWd-Yo-2UOKJrzkedUaDKDNl4Ve8cwEeEdTkRxExZ8Nffx4jgbobURAbDmTCAeEO9Rt8U_EVD9lfQRBION9Lxpz3giOloHAgXoXrrUaOTz2OfbzFqf3UKrQiBSdZCPxqZ5d8d0prXap6q-1Tg4koF4nEo2csKRXV8WUhOkMu_SBk6heaO-gxqHWMVpnvnF11M8935M0QRJhDFsadnRPrdoATD8iTgnM_CGkiTy1yqnsojqNL8LQoKGA9JC-T7aK9L96ZtlEQ',
    isMegaProject: false,
    isDefault: true,
  },
  {
    projectName: 'Greenwood Villas Estate',
    location: 'Bangalore, Karnataka',
    city: 'Bangalore',
    district: 'Bangalore',
    category: 'residential',
    systemSizeKw: 15,
    description: 'Residential solar installation for estate',
    caseStudy: '',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAX7h8bsynujTruSXAtsPopkEW-rDb3fU4t5u77f6960JKi-h7QT7mq7754adZ1otM3m6y9ZlSykFlzpL9yNyxj6AwoJT-qo2adsOFtq-tYL-1hqGdUj_EgGGqpzynLW1U-2Kqp14TBCzr84RPWZpAZAykQwWCxJVoXg7N-oGl7vcesEjFQmNg915RM_FPxeWZrbHkDXpS2Rb0GgCzzijDXTpiC6UPVFztHFh1XqXzYeYYN7gGY2G6IrnLRvW_BeCWfbdD3NNWbUykN',
    isMegaProject: false,
    isDefault: true,
  },
  {
    projectName: 'Agri-Solar Cooperative',
    location: 'Nashik, Maharashtra',
    city: 'Nashik',
    district: 'Nashik',
    category: 'industrial',
    systemSizeKw: 120,
    description: 'Agricultural solar cooperative project',
    caseStudy: '',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB3FldUNFr-_sZMhcLeYAIGZ3oOQfCsrmnJhMWDplpEXPojydRNUmJtnbTfgmmoMpJY6w20dwoH4yCK6kciiERR-0GSssupekfU0cdkGOjmY_aoW-Ko1iL2nzDVz48hYJip0Yd2cLxdJU08LlgTn15rDObHP3gLZv16slG0vvwXM-bMZQT9y21CBWSm89VSLKeYozwRPdjyTCGpcdVUHl5DA3k8TZJKqFZinZDB7GVMJbZtDCW2IqoW5rhOJA5s169D8noWkBrh12X2',
    isMegaProject: false,
    isDefault: true,
  },
  {
    projectName: 'City Care Hospital Network',
    location: 'Delhi, NCR',
    city: 'Delhi',
    district: 'Delhi',
    category: 'commercial',
    systemSizeKw: 350,
    description: 'Hospital network solar installation',
    caseStudy: '',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuASN1AWid6MSqro7nMoUG5ifYMh1wL08eCzaHaOTQnskR8zhlvHca3bKSJqtRugDArJz0rEOUw72jLqUMg8G76s_EXzRWWaHGjYHrHNGO1SrmuYnSedV8JZucAIIQVCENTTR-pEeEnEX6ix4EjIvVVpUDXLm9mlkyy03KSfl0xTDh0rOxf-oYfRxV8kCf7pgE0aJHB4sFn0U93aRJEs4jl9Tfzgs175OX65XJiDuGia9WTw7s03Sg5mqxAwYcHX8SSXbeUetQnwUHZq',
    isMegaProject: false,
    isDefault: true,
  },
  {
    projectName: 'Global International School',
    location: 'Chennai, Tamil Nadu',
    city: 'Chennai',
    district: 'Chennai',
    category: 'commercial',
    systemSizeKw: 80,
    description: 'School solar installation system',
    caseStudy: '',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCMweeFViKHYV4Td4956t8_tZ4qmvr65Vh0MdSebaHoQmy9va8fT89QzCdXvapDFHyc5MqPqacnHLYQuQd0FPTv2ZLut-mAyr1LeDnOjwT7Y1E6hYHwTefHzSWKzTx_klGigGFM2FyBF2O4fN6xzgREBHe4kElBR8GiVBc-lkR4_9Pocr8HLUDnDhyGxnzz_hnLD1mHCCv_3soPx0bYM-u-13uxoUZp6OLM9DeK9ynktyUFxCDnfppamcQ3_xXXcG02eHBAaJ4nQ-69',
    isMegaProject: false,
    isDefault: true,
  },
  {
    projectName: 'Mega Solar Park X',
    location: 'Ahmedabad, Gujarat',
    city: 'Ahmedabad',
    district: 'Ahmedabad',
    category: 'industrial',
    systemSizeKw: 10000,
    description: 'A large-scale ground-mounted installation built with bifacal modules and single-axis trackers to maximize yield.',
    caseStudy: '',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBskYFI-VdwFZTEG3XqipEec3An4I6EE6U9qe6AvqOSBnrEzhRMPjmr4ymrg1ydiHUsK4gLk4cMP2h6njFuXv6CvnWThUQ1UM5CSDjeQrY33gpyfyH0br2uGMEJjrIAQQwZYDC8zaezmaKFuj42YxtQZ76zr2hS5f85jFo9o_Y_en8rip49vGC_N3VIh3-e1T27ICe99iLhba_I4Q28GdUDNPRck1BmEtVf8MZe6TP3Vk2whCnv0uNe_awNWBomySflm1TNOvelpUN5',
    isMegaProject: true,
    isDefault: true,
  },
];

const defaultTeamMembers = [
  {
    name: 'Arjun Mehta',
    role: 'Founder & CEO',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAu-Q_yZsZR16QXrw9RL9GgigopRWwQMFRNQ3uRa9LduEF8N0eKNXKF0dP7tcbtq0UG7HEWVNuxwFbOg2QHhN5Btrj55ew6rgKaD26bh2SAcFPEPAov5v66usLz6vtKN7seZu7gB9HOGdaQrzKLRFT5IbhDGD2de3L-AJ3h6MkOvDvfvExlV3F5dSmmFYmPFVa6aCd6gkKMAU-qnRw1dRwaQQKD4p0uAD68yTRS0cl4fADrk2BZDYNn5a1Ll4vk1i5GiEKZZK10vRoO',
    virtualCardLink: '',
    isDefault: true,
  },
  {
    name: 'Priya Sharma',
    role: 'Head of Engineering',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDPlnC99A_Qid0GK6iiNZUChUkt9MJHhJonOSS31K2USns8ValWAE1Wm1Q3Wr1kIgyEC50SxEvN0l-Cnc7FQaiQPH9t2Mad2n3-8mqLpRq8q9FB-i4gbBuBhzG2hCnpAejklZWQmLX4zogmzikLUDh4Lqzn60qWcA9hJ1cK4R-AHPI6fPlH8VCj7mLWxy0pHF0f0nYBSQlQsar0jDvNyfL_jeMAjQNLaL3IeZxenAOyWhsZKIq1d6m-gOqTmuCotnm5zymxUu-v8aGZ',
    virtualCardLink: '',
    isDefault: true,
  },
  {
    name: 'Vikram Singh',
    role: 'Operations Director',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCmHexMCh70P7DsMtqB5j8gzMx5CFwjuF_quV5TP5dzGBs3l_FRjd2RhgngstKnNeJTAq4xg5iN_k24WWBd4Ic8apCKTGdWXkQJJtxCulxCo2WukabmSxyK8fWT5Tkos3pwK8dxBBBrd2WXdfO88lYHGFh7AyOnC47ug7WCjioAQdFee4cXclv27dA-B9LizhS5zmVBrMx1Dd_mOkcpWNMHNF222we970FqGh5Fj6afuQ4ahRadd9E-pquZVorHsiAZbt9o2pyTlhgh',
    virtualCardLink: '',
    isDefault: true,
  },
];

module.exports = {
  defaultProjects,
  defaultTeamMembers,
};
